---
- name: Roll back image mode host
  hosts: image_mode_hosts
  become: true
  serial: 5

  tasks:
    - name: Roll back to previous deployment
      ansible.builtin.command:
        cmd: bootc rollback

    - name: Reboot after rollback
      ansible.builtin.reboot:
        reboot_timeout: 900