---
controller_hosts:

  - name: image-builder-01
    inventory: "Image Builders"
    enabled: true

    variables:
      ansible_host: 172.31.0.10
      ansible_user: ec2-user

  - name: image-dev-01
    inventory: "Image Mode Development"
    enabled: true

    variables:
      ansible_host: 172.31.0.20
      ansible_user: ec2-user