[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=/Users/phil/Documents/Git Projects/image-mode-hackathon-setup/image-mode-lab-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

aws_region=us-east-2
secret_prefix=image-mode-lab
aws_profile=image-mode-lab

aws_dns_resolver=10.20.0.2

parent_domain_name=sandbox4075.opentlc.com
idm_domain_name=lab.sandbox4075.opentlc.com
idm_realm_name=LAB.SANDBOX4075.OPENTLC.COM
idm_server_fqdn=idm-1.lab.sandbox4075.opentlc.com
idm_server_ip=10.20.1.109

############################################################
# IdM Users
############################################################

idm_users=["claudiol","pduncan","cpranava","stripura"]


[idm]
idm-1.lab.sandbox4075.opentlc.com ansible_host=18.222.19.237 private_ip=10.20.1.109


[satellite]
satellite-1.lab.sandbox4075.opentlc.com ansible_host=18.227.133.182 private_ip=10.20.1.61


[aap]
aap-1.lab.sandbox4075.opentlc.com ansible_host=3.20.121.153 private_ip=10.20.1.42


[quay]
quay-1.lab.sandbox4075.opentlc.com ansible_host=3.151.206.76 private_ip=10.20.1.62


[image_builder]
image-builder-1.lab.sandbox4075.opentlc.com ansible_host=3.14.108.185 private_ip=10.20.1.85
