############################################################
# Server Information
############################################################

output "servers" {
  description = "Created lab servers with hostname, role, private IP, persistent Elastic IP, FQDN, and SSH command."

  value = {
    for name, instance in aws_instance.server :
    name => {
      hostname   = instance.tags.Name
      fqdn       = local.flattened_servers[name].hostname
      role       = instance.tags.Role
      private_ip = instance.private_ip
      public_ip  = aws_eip.server[name].public_ip

      ssh = "ssh -i ${local.ansible_ssh_private_key_file} ec2-user@${aws_eip.server[name].public_ip}"
    }
  }
}

############################################################
# Generated SSH Key Information
############################################################

output "lab_ssh_key_pair_name" {
  description = "AWS EC2 key pair name generated by Terraform."
  value       = aws_key_pair.lab.key_name
}

output "lab_ssh_private_key_file" {
  description = "Local sensitive private key file used by Terraform local-exec and Ansible."
  value       = local.ansible_ssh_private_key_file
}

output "lab_ssh_private_key_secret_name" {
  description = "AWS Secrets Manager secret name containing the generated lab SSH private key."
  value       = local.lab_ssh_private_key_secret_name
}

############################################################
# Generated Ansible Inventory
############################################################

output "ansible_inventory" {
  description = "Dynamic Ansible inventory generated from Terraform-created AWS servers."

  value = templatefile("${path.module}/inventory.tpl", {
    aws_dns_resolver             = local.aws_dns_resolver
    ansible_ssh_private_key_file = local.ansible_ssh_private_key_file

    aws_region    = var.aws_region
    aws_profile   = var.aws_profile
    secret_prefix = var.secret_prefix

    lab_ssh_private_key_secret_name = local.lab_ssh_private_key_secret_name

    lab_users = var.lab_users
    idm_users = var.idm_users

    parent_domain_name = local.parent_domain_name
    idm_domain_name    = local.idm_domain_name
    idm_realm_name     = local.idm_realm_name
    idm_server_fqdn    = local.flattened_servers["idm-1"].hostname
    idm_server_ip      = aws_instance.server["idm-1"].private_ip

    servers = {
      for name, instance in aws_instance.server :
      name => {
        hostname   = instance.tags.Name
        fqdn       = local.flattened_servers[name].hostname
        role       = instance.tags.Role
        private_ip = instance.private_ip
        public_ip  = aws_eip.server[name].public_ip
      }
    }
  })
}

############################################################
# AWS Network Information
############################################################

output "vpc_id" {
  description = "Created VPC ID."
  value       = aws_vpc.lab.id
}

output "vpc_cidr" {
  description = "Created VPC CIDR block."
  value       = aws_vpc.lab.cidr_block
}

output "aws_dns_resolver" {
  description = "AWS VPC DNS resolver address, normally VPC CIDR base + 2."
  value       = local.aws_dns_resolver
}

output "public_subnet_id" {
  description = "Created public subnet ID."
  value       = aws_subnet.public.id
}

output "resolver_subnet_id" {
  description = "Second subnet ID used by the Route53 Resolver outbound endpoint."
  value       = aws_subnet.resolver.id
}

output "security_group_id" {
  description = "Created lab security group ID."
  value       = aws_security_group.lab.id
}

############################################################
# DNS Information
############################################################

output "parent_domain_name" {
  description = "Effective OpenTLC parent DNS domain discovered or provided for this lab."
  value       = local.parent_domain_name
}

output "idm_domain_name" {
  description = "IdM-managed DNS domain."
  value       = local.idm_domain_name
}

output "idm_realm_name" {
  description = "IdM Kerberos realm name."
  value       = local.idm_realm_name
}

output "public_dns_zone_id" {
  description = "Public Route53 hosted zone ID used for public DNS records."
  value       = local.public_route53_zone_id
}

output "route53_resolver_endpoint_id" {
  description = "Route53 Resolver outbound endpoint ID used to forward IdM DNS queries."
  value       = aws_route53_resolver_endpoint.outbound.id
}

output "route53_resolver_rule_id" {
  description = "Route53 Resolver rule ID forwarding the IdM DNS zone to the IdM server."
  value       = aws_route53_resolver_rule.idm_forward.id
}

output "route53_resolver_forward_domain" {
  description = "DNS domain forwarded from AWS Resolver to IdM DNS."
  value       = local.idm_domain_name
}

output "route53_resolver_forward_target" {
  description = "Private IP of the IdM DNS server used as the Route53 Resolver forwarding target."
  value       = aws_instance.server["idm-1"].private_ip
}

output "server_fqdns" {
  description = "FQDNs created for lab servers."

  value = {
    for name, server in local.flattened_servers :
    name => server.hostname
  }
}

############################################################
# Useful Connection Summary
############################################################

output "ssh_commands" {
  description = "Quick SSH commands for created instances."

  value = {
    for name, instance in aws_instance.server :
    name => "ssh -i ${local.ansible_ssh_private_key_file} ec2-user@${aws_eip.server[name].public_ip}"
  }
}

output "aap_url" {
  description = "AAP URL."
  value       = "https://aap-1.${local.idm_domain_name}"
}

output "quay_url" {
  description = "Quay URL."
  value       = "https://quay-1.${local.idm_domain_name}"
}

output "satellite_url" {
  description = "Satellite URL."
  value       = "https://satellite-1.${local.idm_domain_name}"
}

output "idm_fqdn" {
  description = "IdM server FQDN."
  value       = "idm-1.${local.idm_domain_name}"
}

output "image_builder_fqdn" {
  description = "Image builder server FQDN."
  value       = "image-builder-1.${local.idm_domain_name}"
}