############################################################
# Server Information
############################################################

output "servers" {
  description = "Created lab servers with hostname, role, private IP, persistent Elastic IP, FQDN, and SSH command."

  value = {
    for name, instance in aws_instance.server :
    name => {
      hostname   = instance.tags.Name
      fqdn       = local.flattened_servers[name].hostname
      role       = instance.tags.Role
      private_ip = instance.private_ip
      public_ip  = aws_eip.server[name].public_ip

      ssh = "ssh -i ${local.ansible_ssh_private_key_file} ec2-user@${aws_eip.server[name].public_ip}"
    }
  }
}

############################################################
# Generated SSH Key Information
############################################################

output "lab_ssh_key_pair_name" {
  description = "AWS EC2 key pair name generated by Terraform."
  value       = aws_key_pair.lab.key_name
}

output "lab_ssh_private_key_file" {
  description = "Local sensitive private key file used by Terraform local-exec and Ansible."
  value       = local.ansible_ssh_private_key_file
}

output "lab_ssh_private_key_secret_name" {
  description = "AWS Secrets Manager secret name containing the generated lab SSH private key."
  value       = local.lab_ssh_private_key_secret_name
}

############################################################
# Generated Ansible Inventory
############################################################

output "ansible_inventory" {
  description = "Dynamic Ansible inventory generated from Terraform-created AWS servers."

  value = templatefile("${path.module}/inventory.tpl", {
    aws_dns_resolver             = local.aws_dns_resolver
    ansible_ssh_private_key_file = local.ansible_ssh_private_key_file

    aws_region    = var.aws_region
    aws_profile   = var.aws_profile
    secret_prefix = var.secret_prefix

    lab_ssh_private_key_secret_name = local.lab_ssh_private_key_secret_name

    lab_users = var.lab_users
    idm_users = var.idm_users

    parent_domain_name = local.parent_domain_name
    idm_domain_name    = local.idm_domain_name
    idm_realm_name     = local.idm_realm_name

    idm_server_fqdn = local.flattened_servers[sort([
      for name, server in local.flattened_servers :
      name
      if server.role == "idm"
    ])[0]].hostname

    idm_server_ip = aws_instance.server[sort([
      for name, server in local.flattened_servers :
      name
      if server.role == "idm"
    ])[0]].private_ip

    servers = {
      for name, instance in aws_instance.server :
      name => {
        hostname   = instance.tags.Name
        fqdn       = local.flattened_servers[name].hostname
        role       = instance.tags.Role
        private_ip = instance.private_ip
        public_ip  = aws_eip.server[name].public_ip
      }
    }
  })
}

############################################################
# AWS Network Information
############################################################

output "vpc_id" {
  description = "Created VPC ID."
  value       = aws_vpc.lab.id
}

output "vpc_cidr" {
  description = "Created VPC CIDR block."
  value       = aws_vpc.lab.cidr_block
}

output "aws_dns_resolver" {
  description = "AWS VPC DNS resolver address, normally VPC CIDR base + 2."
  value       = local.aws_dns_resolver
}

output "public_subnet_id" {
  description = "Created public subnet ID."
  value       = aws_subnet.public.id
}

output "resolver_subnet_id" {
  description = "Second subnet ID used by the Route53 Resolver outbound endpoint."
  value       = aws_subnet.resolver.id
}

output "security_group_id" {
  description = "Created lab security group ID."
  value       = aws_security_group.lab.id
}

############################################################
# DNS Information
############################################################

output "parent_domain_name" {
  description = "Effective OpenTLC parent DNS domain discovered or provided for this lab."
  value       = local.parent_domain_name
}

output "idm_domain_name" {
  description = "IdM-managed DNS domain."
  value       = local.idm_domain_name
}

output "idm_realm_name" {
  description = "IdM Kerberos realm name."
  value       = local.idm_realm_name
}

output "public_dns_zone_id" {
  description = "Public Route53 hosted zone ID used for public DNS records."
  value       = local.public_route53_zone_id
}

output "route53_resolver_endpoint_id" {
  description = "Route53 Resolver outbound endpoint ID used to forward IdM DNS queries."
  value       = aws_route53_resolver_endpoint.outbound.id
}

output "route53_resolver_rule_id" {
  description = "Route53 Resolver rule ID forwarding the IdM DNS zone to the IdM server."
  value       = aws_route53_resolver_rule.idm_forward.id
}

output "route53_resolver_forward_domain" {
  description = "DNS domain forwarded from AWS Resolver to IdM DNS."
  value       = local.idm_domain_name
}

output "route53_resolver_forward_target" {
  description = "Private IP of the selected primary IdM DNS server used as the Route53 Resolver forwarding target."

  value = aws_instance.server[sort([
    for name, server in local.flattened_servers :
    name
    if server.role == "idm"
  ])[0]].private_ip
}

output "server_fqdns" {
  description = "FQDNs created for lab servers."

  value = {
    for name, server in local.flattened_servers :
    name => server.hostname
  }
}

############################################################
# Role-Based Server Information
############################################################

output "idm_servers" {
  description = "Created IdM servers."

  value = {
    for name, instance in aws_instance.server :
    name => {
      hostname   = local.flattened_servers[name].hostname
      private_ip = instance.private_ip
      public_ip  = aws_eip.server[name].public_ip
      url        = "https://${local.flattened_servers[name].hostname}"
    }
    if local.flattened_servers[name].role == "idm"
  }
}

output "aap_servers" {
  description = "Created AAP servers."

  value = {
    for name, instance in aws_instance.server :
    name => {
      hostname   = local.flattened_servers[name].hostname
      private_ip = instance.private_ip
      public_ip  = aws_eip.server[name].public_ip
      url        = "https://${local.flattened_servers[name].hostname}"
    }
    if local.flattened_servers[name].role == "aap"
  }
}

output "quay_servers" {
  description = "Created Quay servers."

  value = {
    for name, instance in aws_instance.server :
    name => {
      hostname   = local.flattened_servers[name].hostname
      private_ip = instance.private_ip
      public_ip  = aws_eip.server[name].public_ip
      url        = "https://${local.flattened_servers[name].hostname}"
    }
    if local.flattened_servers[name].role == "quay"
  }
}

output "satellite_servers" {
  description = "Created Satellite servers."

  value = {
    for name, instance in aws_instance.server :
    name => {
      hostname   = local.flattened_servers[name].hostname
      private_ip = instance.private_ip
      public_ip  = aws_eip.server[name].public_ip
      url        = "https://${local.flattened_servers[name].hostname}"
    }
    if local.flattened_servers[name].role == "satellite"
  }
}

output "image_builder_servers" {
  description = "Created image builder servers."

  value = {
    for name, instance in aws_instance.server :
    name => {
      hostname   = local.flattened_servers[name].hostname
      private_ip = instance.private_ip
      public_ip  = aws_eip.server[name].public_ip
      url        = "https://${local.flattened_servers[name].hostname}"
    }
    if local.flattened_servers[name].role == "image-builder"
  }
}

############################################################
# Primary Service Endpoints
############################################################

output "primary_idm_fqdn" {
  description = "Primary IdM server FQDN selected dynamically."

  value = local.flattened_servers[sort([
    for name, server in local.flattened_servers :
    name
    if server.role == "idm"
  ])[0]].hostname
}

output "primary_idm_private_ip" {
  description = "Primary IdM server private IP selected dynamically."

  value = aws_instance.server[sort([
    for name, server in local.flattened_servers :
    name
    if server.role == "idm"
  ])[0]].private_ip
}

output "aap_urls" {
  description = "AAP URLs."

  value = {
    for name, server in local.flattened_servers :
    name => "https://${server.hostname}"
    if server.role == "aap"
  }
}

output "quay_urls" {
  description = "Quay URLs."

  value = {
    for name, server in local.flattened_servers :
    name => "https://${server.hostname}"
    if server.role == "quay"
  }
}

output "satellite_urls" {
  description = "Satellite URLs."

  value = {
    for name, server in local.flattened_servers :
    name => "https://${server.hostname}"
    if server.role == "satellite"
  }
}

output "image_builder_fqdns" {
  description = "Image builder FQDNs."

  value = {
    for name, server in local.flattened_servers :
    name => server.hostname
    if server.role == "image-builder"
  }
}

############################################################
# Quay IdM LDAP Information
############################################################

output "quay_idm_ldap_settings" {
  description = "Derived IdM LDAP settings used by Quay."

  value = {
    ldap_uri = "ldap://${local.flattened_servers[sort([
      for name, server in local.flattened_servers :
      name
      if server.role == "idm"
    ])[0]].hostname}:389"

    ldap_base_dn   = join(",", [for part in split(".", local.idm_domain_name) : "dc=${part}"])
    ldap_bind_user = "uid=admin,cn=users,cn=accounts,${join(",", [for part in split(".", local.idm_domain_name) : "dc=${part}"])}"
    admin_users    = var.idm_users
  }
}

############################################################
# AWS Secrets Manager Secret Names
############################################################

output "quay_secret_names" {
  description = "AWS Secrets Manager secret names used by the Quay deployment."

  value = {
    db_password        = "${var.secret_prefix}/quay/db_password"
    secret_key         = "${var.secret_prefix}/quay/secret_key"
    superuser          = "${var.secret_prefix}/quay/superuser"
    superuser_password = "${var.secret_prefix}/quay/superuser_password"
    admin_access_token = "${var.secret_prefix}/quay/admin_access_token"
    registry_username  = "${var.secret_prefix}/redhat/registry_username"
    registry_password  = "${var.secret_prefix}/redhat/registry_password"
    idm_admin_password = "${var.secret_prefix}/idm/admin_password"
  }
}

############################################################
# Useful Connection Summary
############################################################

output "ssh_commands" {
  description = "Quick SSH commands for created instances."

  value = {
    for name, instance in aws_instance.server :
    name => "ssh -i ${local.ansible_ssh_private_key_file} ec2-user@${aws_eip.server[name].public_ip}"
  }
}