---
- name: Configure AAP Image Mode CI/CD
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - infra.aap_configuration
    - ansible.controller

  vars_files:
    - vars/aap-auth.yml
    - vars/image-mode-inventory.yml
    - vars/image-mode-credentials.yml
    - vars/image-mode-projects.yml
    - vars/image-mode-job-templates.yml
    - vars/image-mode-workflows.yml

  roles:
    - infra.aap_configuration.controller_organizations
    - infra.aap_configuration.controller_credentials
    - infra.aap_configuration.controller_inventories
    - infra.aap_configuration.controller_hosts
    - infra.aap_configuration.controller_projects
    - infra.aap_configuration.controller_job_templates
    - infra.aap_configuration.controller_workflow_job_templates